### ISSUE TITLE
As PO I want to simulate that I am a user willing to access into Polygon DAO first and later on use Sushiswap services

### ISSUE THREAD

**Issue by aransil** [privadonetwork/privado-wallet#65]
## Design reference
![image.png](https://images.zenhubusercontent.com/6074079d663f8db77467d195/a950a643-93cf-424e-9e3f-c3a112e94d23)
TBC

## Acceptance criteria
Modify the url from deversifi to polygondao: https://wizard.sandbox.privadoid.com/examples/polygondao.html
Change Deverisfi logo and use Polygon's one
Modify the message and replace Deversifi by PolygonDAO

## Technical implementation

- [x] change logo
- [x] change background color
- [x] add new icon

## Test steps

In the Verification Wizard project:
- [ ] in command line, enter in the examples folder and run it using [serve](https://www.npmjs.com/package/serve)
- [ ] click on the Polygon file
- [ ] check the layout
- [ ] do the onboarding process

In the Wallet project:
- [ ] login into the wallet using the link that you received after the onboarding
- [ ] click on Polygon card
- [ ] check the description and the logo

**Comment by aransil** [comment]
The logo can be found here: https://polygon.technology/brand-resources/

**Comment by gustavoeffting** [comment]
Finished the frontend part. I've opened a Draft pull request until the backend updates the info to test the whole flow properly.
